name: Django CI

on: # 액션이 언제 실행되는 지를 정의 한다. 
  push: # 푸시 할때마~

jobs: # 하나의 workflow는 여러개의  job으로 구성된다.
  ci: # 이 workflow의 1개의 job이 있고, job의 이름은 ci 이다.
    runs-on: ubuntu-latest # github action은 여러가지 머신을 제공한다. 그 중 하나인 ubuntu-latest 사용한다.
    steps: # job은 여러개의 step으로 구성된다. step은 명령을 실행하거나 다른 action을 실행한다.
      - name: Check out the codes
        uses: actions/checkout@v2 # step에서 다른 명령어를 실행하고 싶으면 uses 키워드를 쓴다.

      - name: Setup python environment
        id: setup-python
        uses: actions/setup-python@v2
        with: # uses를 사용할때 with를 같이 사용할 수 있다. with는 uses에 전달할 prameter이다.
          python-version: 3.9.9
          # 위의 로직을 말로 풀이하자면 python을 setup하려고 하는데, 파이썬의 버전은 3.9.9로 할 것이다. 라고 말하는 것가 같다.

      - name: Install Poetry
        run: | # run은 실행할 명령어이다.
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          echo "${HOME}/.poetry/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: | #run에서 |(파이프라인)은 yaml의 문법이다. value가 여러 줄 이라는 것을 의미한다.
          ${HOME}/.poetry/bin/poetry install

      # - name: Test python project
      #   run: |
      #     poetry run python manage.py test
